repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    - id: ruff
      args:
        [
          --fix,
          --exit-non-zero-on-fix,
        ]
    - id: ruff-format
      args: [--check]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    args: ["--config-file", "pyproject.toml"]
    additional_dependencies: ["pydantic>=2.9.2"]

- repo: https://github.com/jendrikseipp/vulture
  rev: v2.11
  hooks:
  - id: vulture
    args: ["src/", "--min-confidence", "80"]
